version: '3.1'

services:
    php: 
        image: php:7.0-apache
        ports: 
            - 8081:80
        volumes:
            - /home/hunsche/Dropbox/engenharia-da-computacao/programacao-web/a2-programacao-web/meudindin:/var/www/html/
